dist: trusty

language: java

jdk:
  - oraclejdk8

script:
  - mvn clean install
  - "mvn cobertura:cobertura"
notifications:
  email: false
  slack: "A2S2iVqRkG0MFnqFT3+sLCt1/3VoHlqCrnMNwQfvW2uxreBBkvY1zdPxIIFUVvzpSCuebY2zoi56lCz3COPJS1T4xiMUpu5hy5QT4S4YulO4IytXAtD3wDRvX+IS9slDz+zCLPrzJJxiZRv4Hr489s0Yy55lF9HYdiIdRcg6eFMhEOFnynibt+JVVM5/UTniqfHKat/mc+aG16gGjugIUtvdiaSfLHCi68nJ0ZzqspbytjYNu6EfNTxJe/BBR9gnE6owcrTOFeXI3cmQe7JyTeCggTcaPbNMFCvRV1XnEQ6C9p1ECLN4b4yot3RbPaAFp1FzY825h70kCSp9d2QU6fqY933gSGvgj2o8A3/NrE5xY5QsvqkxiNvmacVNPIa8WyXWP8xSKJLSLGGaCA3ehd2J00+e21Ye9V7w9YOtymlRxj38ejCHWjxzKCMYWAuaiEnUxNFKUPXUFu1haLPJaoRkhh5cv816mSgGjCD2YM5G9T3FEukjeGHV52onl4x6rLAOuwQVeG42SgaVP7PoisWojbYTA+64Cz3ppnKrWfqikBXtSdkP8+tj8s3IU2Z8eSv+1anDTSd6ZyJubByzDDXnuYce7xnUq7wm8BCx8zzVFTFf1mpLLPnuy115YYebBLFDI4xZ8Wq1jVulTamZj2pBbw/JGUP5ZrNIl2K+ZKE="

after_success:
  - bash <(curl -s https://codecov.io/bash)
