dist: trusty

language: java

jdk:
  - oraclejdk8

script:
  - mvn clean install
  - "mvn cobertura:cobertura"

notifications:
    email: false        # default notif method deactivated
    slack: group-22-corp:zytnrBUqQyk0xFZbW4eValQD
    
after_success:
  - bash <(curl -s https://codecov.io/bash)
